apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee-api
  template:
    metadata:
      labels:
        app: coffee-api
    spec:
      containers:
      - name: coffee-api
        image: ghcr.io/butusikbestdevops/coffe-api:pr-1
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: PG_DB
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: PG_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: PG_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-api-service
spec:
  type: NodePort
  selector:
    app: coffee-api
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30574
